### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by ThomasAdam** [OrdnanceSurvey/Boundary-Line-stylesheets#1]
Hello,

This repository is missing a LISENSE file, detailing which licence the files contained within this repository belong to.

**Comment by charleyglynn** [comment]
Hi Thomas,

The license for the stylesheets is in the top level of the repo: https://github.com/OrdnanceSurvey/Boundary-Line-stylesheets/blob/master/stylesheet-licence-v2.pdf

It covers any stylesheets that sit within the repo.

Cheers

**Comment by ThomasAdam** [comment]
Hi,

I understand that, but it's really not clear just from first clone of the repository.  I shouldn't have to go digging into random PDF files to ascertain this.  Github's own recommendations on this are here:

https://help.github.com/articles/open-source-licensing/

While I appreciate the licence is at least contained _somewhere_ I would strongly urge you to make this much more obvious, especially if you want people to use your data in a way which is in accordance with the license you've given the data, and without any unnecessary assumptions.

**Comment by charleyglynn** [comment]
Thanks for the feedback Thomas.  [We recently announced that we are adopting the OGL v3.0](https://www.ordnancesurvey.co.uk/blog/2015/02/were-using-the-open-government-licence-to-encourage-greater-use-of-os-opendata-products/) and our plan is to roll this out to our stylesheets too. 

When we do that we will take your feedback on board

Cheers

Charley
